include:

  # Static Application Security Testing
  - template: SAST.gitlab-ci.yml

  # Check dependencies for potential problems
  - template: Dependency-Scanning.gitlab-ci.yml

  # License Scanning; Overkill, but shouldn't hurt
  - template: License-Scanning.gitlab-ci.yml
